### ISSUE TITLE
Building on OSX

### ISSUE THREAD

**Issue by manderss99** [cardigann/cardigann#130]
I'd like to build cardigan myself and add a tracker.
I have installed golang and cloned git repository.
When I try to make the project it fails due to missing esc and rpm executables.

**Comment by lxt2** [comment]
I just pushed a commit to master that adds a `make setup` target to the Makefile. You can use that to install dependencies.

Btw, you don't need to build cardigann to develop indexer definitions, they are just YAML files: https://github.com/cardigann/cardigann/tree/master/definitions

Copy one of those locally and then use the `./cardigann test myfile.yml` syntax.

**Comment by manderss99** [comment]
still gets error:

Mac:cardigann manderss99$ make setup
go get -u github.com/mjibson/esc
go get -u github.com/c4milo/github-release
Mac:cardigann manderss99$ make build
cd web; npm run build
/bin/sh: npm: command not found
make: *** [server/static.go] Error 127
