### ISSUE TITLE
Failed to match selector.

### ISSUE THREAD

**Issue by darkcloud784** [cardigann/cardigann#201]
This is in reference to bug #167 which was closed. After the "fix" was added I get the following..

Failed to match selector "a[href^=\"download.php\"]"

**Comment by kaso17** [comment]
@darkcloud784 please check if you see the download links on funfile directly. Your download rights might have been removed. It can happen very easily on funfile (a single Hit and Run for example).

**Comment by darkcloud784** [comment]
@kaso17 I totally overlooked this, thanks for setting me straight.

**Comment by darkcloud784** [comment]
After ensuring my H&R rate is not a problem. I got this when testing funfile - Failed to match selector "div:has(div#clock) > b:last-child"
I am on the Edge build 1.9.3-20-g871e7c1.

**Comment by kaso17** [comment]
This was fixed in #194, not sure why it's not part of the latest edge build

**Comment by darkcloud784** [comment]
This issue is obviously not resolved since its still giving the same error in the edge build which per the previous commit it has been merged into the edge. Maybe this is something @lxt2  can look at?

**Comment by kaso17** [comment]
@darkcloud784 
Just wait for the next build.
If you look at the source it has been fixed, just didn't make it into a binary build yet:
https://github.com/cardigann/cardigann/blob/master/definitions/funfile.yml#L41
This error only affects the ratio parsing, normal search should work fine.

**Comment by lxt2** [comment]
That's very odd, every build should make it into edge.

**Comment by lxt2** [comment]
This is the latest build that went out: https://travis-ci.org/cardigann/cardigann/jobs/177252212

**Comment by lxt2** [comment]
1.9.3-27-ga286c6d is the latest. I'll put out a stable now.

**Comment by lxt2** [comment]
1.9.4 is here https://travis-ci.org/cardigann/cardigann/builds/177364132
